name: mac
on: [push]

jobs:
  main:
    name: main
    runs-on: macOS-${{ matrix.os-version }}

    strategy:
      matrix:
        os-version:
          - '10.14'
        python-version:
          - '2.7'
          - '3.6'
          - '3.7'
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Ruby
        uses: actions/setup-ruby@v1

      - name: Install brew
        run: |
          /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

      - name: Install Rez
        run: |
          mkdir ./build
          python ./install.py ./build

      - name: Run Rez Tests
        run: |
          ./build/bin/rez/rez-selftest
