name: ubuntu-16.04
on: [push]

jobs:
  main:
    name: main
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        python-version: ['2.7']

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rez
        run: |
          mkdir ./build
          python ./install.py ./build

      - name: Run Tests
        run: |
          ./build/bin/rez/rez-selftest
